# Site settings
title: Jonas Reitmann
email: jonas@reitmann.me
description: Jonas Reitmann
baseurl: ""
url: "http://jonas.re" # the base hostname & protocol for your site
twitter_username: jonicious
github_username:  jonicious

# Build settings
markdown: kramdown
exclude: [
  "/node_modules",
  "gulpfile.js",
  "package.json",
  "README.md",
  "/css/style.scss"
]

keep_files: [
  "css/style.css",
  "_site/.htaccess"
]
